branches:
  only:
    - master

language: generic

services:
  - docker
sudo: required

env:
  - DEP="gnuradio" PKG="libad9361-iio-git gnuradio-iio-git gnuradio-osmosdr-gqrx-git gqrx-git"
  - PKG="nlohmann-json-bin pothos-git"

script: make

