language: generic

services:
  - docker
sudo: required

addons:
  apt:
    packages:
    - jq

env:
  - PKG_LIST=packages.txt
  - PKG_LIST=packages2.txt

before_install:
  - ./delete-release latest

script: make

before_deploy:
  - git config --local user.name "En Shih"
  - git config --local user.email "seanstone5923@gmail.com"
  - git tag -d $(git tag)
  - git tag latest

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/packages/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: seanstone/arch-on-github

jobs:
  include:
    - stage: "Repo"
      script: make repo
      before_deploy:
        - git config --local user.name "En Shih"
        - git config --local user.email "seanstone5923@gmail.com"
        - git tag -d $(git tag)
        - ./delete-release latest
        - git tag latest
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: repo/*
        file_glob: true
        skip_cleanup: true
        on:
          repo: seanstone/arch-on-github

# - stage: "Build Docker image"
#   script: make image
