branches:
  only:
    - master

language: generic

services:
  - docker
sudo: required

jobs:
  include:
    - stage: "gqrx"
      env:
        - DEP="gnuradio" PKG="rtl-sdr-git libiio-git libad9361-iio-git gnuradio-iio-git libbladerf-git soapysdr-git gnuradio-osmosdr-gqrx-git gqrx-git"
      script: make
      
    - stage: "pothos"
      env:
        - PKG="nlohmann-json-bin pothos-git"
      script: make

