branches:
  only:
    - master
    - dev

language: generic

services:
  - docker
sudo: required

addons:
  apt:
    packages:
    - jq

jobs:
  include:
      
    - stage: "Image"
      script: make image
      
    - &packages
      stage: "Packages"
      env:
        - PKG_LIST=package-lists/packages.txt
      script: make
      before_deploy:
        - &git-config >
          git config --local user.name "En Shih";
          git config --local user.email "seanstone5923@gmail.com";
          git tag -d $(git tag);
        - git tag next
      deploy: &deploy
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/packages/*
        file_glob: true
        skip_cleanup: true
        on:
          repo: seanstone/arch-on-github
          
    - <<: *packages
      env:
        - PKG_LIST=package-lists/packages2.txt
      
    - stage: "Repo"
      script: make repo
      before_deploy:
        - *git-config
        - scripts/delete-release latest
        - git tag latest
      deploy:
        <<: *deploy
        file: repo/*
      after_deploy:
        - scripts/delete-release next
