branches:
  only:
    - master

language: generic

services:
  - docker
sudo: required

env:
  - PKG="rtl-sdr-git libiio-git libad9361-iio-git gnuradio-iio-git libbladerf-git soapysdr-git gnuradio-osmosdr-gqrx-git gqrx-git"
  - PKG="nlohmann-json-bin qwt pothos-git"

script: make
