tags:
  enabled: false

language: generic

services:
  - docker
sudo: required

addons:
  apt:
    packages:
    - jq

jobs:
  include:
    - stage: "Image"
      script: make image

    - stage: "Packages"
      script: make PKG_LIST=package-lists/packages.txt
      script: make PKG_LIST=package-lists/packages2.txt
      before_deploy:
        - git config --local user.name "En Shih"
        - git config --local user.email "seanstone5923@gmail.com"
        - git tag -d $(git tag)
        - git tag next
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/packages/*
        file_glob: true
        skip_cleanup: true
        on:
          repo: seanstone/arch-on-github

    - stage: "Repo"
      script: make repo
      before_deploy:
        - git config --local user.name "En Shih"
        - git config --local user.email "seanstone5923@gmail.com"
        - git tag -d $(git tag)
        - ./delete-release latest
        - git tag latest
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: repo/*
        file_glob: true
        skip_cleanup: true
        on:
          repo: seanstone/arch-on-github
      after_deploy:
        - ./delete-release next
