branches:
  only:
    - master
    - dev

language: generic

services:
  - docker
sudo: required

addons:
  apt:
    packages:
    - jq

jobs:
  include:
      
    - stage: "Image"
      script: make image
      
    - &packages
      stage: "Packages"
      env:
        - PKG_LIST=package-lists/packages.txt
      script: make
