#!/bin/sh -ex

export PKGDEST="$(pwd)/build/packages"
export SRCDEST="$(pwd)/build/sources"

main() {
  while read -r package; do
    build_package "${package}"
  done < packages.txt

  build_repo "$1"
}

build_package() {
  local package="$1"

  if [ -d "build/snapshots/${package}" ]; then
    echo "Already built package ${package}, skipping..."
    return
  fi

  mkdir -p "build/snapshots"
  curl "https://aur.archlinux.org/cgit/aur.git/snapshot/${package}.tar.gz" \
    | tar --extract --gzip --verbose --directory='build/snapshots'

  for dependency in $(get_dependencies "${package}"); do
    if ! package_in_official_repo "$dependency"; then
      build_package "${dependency}"
    fi
  done

  mkdir -p \
    "${PKGDEST}" \
    "${SRCDEST}"
  (cd "build/snapshots/${package}" &&
    makepkg \
      --clean \
      --force \
      --noconfirm \
      --syncdeps)
}

get_dependencies() {
  local package="$1"
  (cd "build/snapshots/${package}" &&
    bash -c 'source PKGBUILD && echo ${depends[@]}')
}

package_in_official_repo() {
  local package="$1"
  pacman --sync --search "^${package}$" > /dev/null
}

build_repo() {
  local repository=$1
  mkdir -p build/repo
  repo-add --new --remove \
    "build/repo/${repository}.db.tar.xz" \
    build/packages/*
}

main "$@"
