#!/bin/sh -ex

fold_start() {
  echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
}

fold_end() {
  echo -e "\ntravis_fold:end:$1\r"
}

while read -r package; do
  fold_start ${package}
  ./build-package "${package}"
  fold_end ${package}
done < "$1"
