#!/bin/sh -ex

export PKGDEST="$(pwd)/build/packages"
export SRCDEST="$(pwd)/build/sources"

main() {
  while read -r package; do
    build_package "${package}"
  done < packages.txt

  build_repo "$1"
}

build_package() {
  local package="$1"

  mkdir -p "build/snapshots"
  curl https://aur.archlinux.org/cgit/aur.git/snapshot/${package}.tar.gz \
    | tar --extract --gzip --verbose --directory='build/snapshots'

  mkdir -p \
    "${PKGDEST}" \
    "${SRCDEST}"
  (cd "build/snapshots/${package}" &&
    makepkg \
      --clean \
      --force \
      --noconfirm \
      --syncdeps)
}

build_repo() {
  local repository=$1
  mkdir -p build/repo
  repo-add --new --remove \
    "build/repo/${repository}.db.tar.xz" \
    build/packages/*
}

main "$@"
