#!/bin/sh -ex

# Deletes a GitHub release using a tag.

API=https://api.github.com

main() {
  local tag="$1"
  local release_url
  release_url="$(get_release_url "${tag}")"
  echo "release url is ${release_url}."
  curl \
    -H "Content-Type: application/json" \
    --user="AlexandreCarlton:${GITHUB_TOKEN}" \
    -X DELETE \
    "${release_url}"
}

get_release_url() {
  local tag="$1"
  curl \
    -H "Content-Type: application/json" \
    --user="AlexandreCarlton:${GITHUB_TOKEN}" \
    "${API}/repos/AlexandreCarlton/arch-on-github/releases/tags/${tag}"
}

main "$@"
