#!/bin/sh -ex

# Deletes a GitHub release using a tag.

API=https://api.github.com

main() {
  local tag="$1"
  local release_url
  release_url="$(get_release_url "${tag}")"
  echo "release url is ${release_url}."
  curl \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -X DELETE "${release_url}"
}

get_release_url() {
  local tag="$1"
  curl \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    "${API}/repos/AlexandreCarlton/arch-on-github/releases/tags/${tag}" \
  | jq --raw-output '.url'
}

if [ -z "${GITHUB_TOKEN}" ]; then
  echo 'Environment variable GITHUB_TOKEN is empty.'
fi

main "$@"
